codecov:
    require_ci_to_pass: true

comment:
    layout: "reach,diff,flags,files,footer"
    behavior: default
    require_changes: false # if true, only comment if coverage changes
    branches:
        - main
        - develop