name: PR Test

on:
    pull_request_target:
        branches:
          [main, develop]
        types:
          [opened, synchronize, reopened]

jobs:
    labeling:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Check Labels
              id: labeler
              uses: jimschubert/labeler-action@v1 # This action references .github/labeler.yml file
              with:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    CITest:
        permissions:
            pull-requests: write
            checks: write
            contents: read

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Set up JDK 17
              uses: actions/setup-java@v4.7.0
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Test with Gradle
              run: ./gradlew clean totalCITest


    checkstyle:
        name: runner / checkstyle
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
            - uses: actions/checkout@v4

            - name: Run checkstyle
            - uses: dbelyaev/action-checkstyle@master
              with:
                  github_token: ${{ secrets.github_token }}
                  reporter: github-pr-review
                  fail_level: error
                  checkstyle_config: ./config/checkstyle/naver-checkstyle-rules.xml
