name: PR Test

on:
    pull_request_target:
        branches:
            - main
            - develop
        types:
            - opened
            - synchronize
            - reopened

jobs:
    labeling:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
        - name: Check Labels
          id: labeler
          uses: jimschubert/labeler-action@v1 # This action references .github/labeler.yml file
          with:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    CITest:
        permissions:
            pull-requests: write
            checks: write
            contents: read

        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.2

        -   name: Clear cache
            uses: actions/github-script@v6
            with:
                script: |
                    console.log("About to clear")
                    const caches = await github.rest.actions.getActionsCacheList({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                    })
                    for (const cache of caches.data.actions_caches) {
                      console.log(cache)
                      github.rest.actions.deleteActionsCacheById({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        cache_id: cache.id,
                      })
                    }
                    console.log("Clear completed")

        - name: Set up JDK 17
          uses: actions/setup-java@v4.7.0
          with:
              java-version: '17'
              distribution: 'temurin'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Test with Gradle
          run: ./gradlew clean totalCITest



        - name: Build and analyze
          run: ./gradlew build jacocoTestReport sonar --info
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
